import axios from "axios";
import Head from 'next/head';
import Home from './home';
import Header from '../components/layout/Header';
import Input from '../components/form/Input';
import Footer from "../components/layout/Footer";


export default function Index({ categoryList, productList }) {
  return (
    <div>
      <Head>
        <title>E-Ticaret Sitesi</title>
        <meta name="description" content="Generated by create next app" />
         
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>      
      <Home categoryList={categoryList} productList={productList} />
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);
  const product = await axios.get(
    `${process.env.NEXT_PUBLIC_API_URL}/products`
  );

  return {
    props: {
      categoryList: res.data ? res.data : [],
      productList: product.data ? product.data : [],
    },
  };
};